export const ODS_THEME_TO_TOPICS: Record<string, string[] | null> = {
  'Enseignement supérieur': ['etudiants-formations', 'etablissements-personnels'],
  'Recherche': ['recherche'],
  'Statistiques': null,
  'Innovation': ['innovation-entreprises'],
  "Établissement d'enseignement supérieur": ['etablissements-personnels'],
  'Nomenclature, référentiel': null,
  'Formations et diplômes': ['etudiants-formations'],
  'Financements': ['financements-europeens', 'recherche', 'etablissements-personnels'],
  'Prix, appels à projets': ['financements-europeens', 'recherche'],
  'Structures publiques de recherche': ['recherche', 'etablissements-personnels'],
  'International': ['financements-europeens', 'etudiants-formations'],
  'Emploi scientifique': ['etablissements-personnels', 'recherche'],
  'Orientation, parcours et réussite': ['etudiants-formations'],
  'Ressources humaines': ['etablissements-personnels'],
  'France entière': ['territoires'],
  'Entreprises': ['innovation-entreprises'],
  'Territoires': ['territoires'],
  'Secteur privé': ['innovation-entreprises'],
  'Pays': ['financements-europeens', 'territoires'],
  'Secteur public': ['recherche', 'etablissements-personnels'],
  'Étudiants': ['etudiants-formations'],
  'Évènements': null,
  'Doctorat': ['etudiants-formations', 'recherche'],
  'Science et société': ['recherche'],
  'Propriété intellectuelle': ['innovation-entreprises'],
  'Vie étudiante': ['etudiants-formations'],
  'Documentation': ['science-ouverte'],
  'Publications scientifiques': ['science-ouverte', 'recherche'],
  'Science ouverte': ['science-ouverte'],
  'Insertion professionnelle': ['insertion-professionnelle'],
  'Entrepreneuriat étudiant': ['innovation-entreprises', 'etudiants-formations'],
  'Pédagogie': ['etudiants-formations'],
  'Apprentissage': ['etudiants-formations', 'insertion-professionnelle'],
  'Finance': ['etablissements-personnels'],
  'Patrimoine immobilier': ['etablissements-personnels'],
};
